### ISSUE TITLE
Server Crash: Entity update causes server to crash and shutdown

### ISSUE THREAD

**Issue by Aeyos** [TeamMetallurgy/Aquaculture#134]
While playing Valhelsia 2 my server has crashed supposedly while ticking an entity. Here's the log

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.PathHeap.func_75846_b(SourceFile:107)
	at net.minecraft.pathfinding.PathHeap.func_75844_c(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_227479_a_(SourceFile:590)
	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:557)
	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:598)
	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:102)
	at net.minecraft.pathfinding.PathNavigator.func_225466_a(PathNavigator.java:92)
	at net.minecraft.entity.ai.goal.AvoidEntityGoal.func_75250_a(SourceFile:67)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75250_a(SourceFile:22)
	at com.performant.coremod.entity.ai.goals.CustomPriotizedSlowedGoal.func_75250_a(CustomPriotizedSlowedGoal.java:52)
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:355)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1310)
	at net.minecraft.entity.passive.fish.AbstractFishEntity.func_70636_d(SourceFile:149)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.passive.fish.AbstractGroupFishEntity.func_70071_h_(SourceFile:75)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)

-- Entity being ticked --
Details:
	Entity Type: aquaculture:muskellunge (com.teammetallurgy.aquaculture.entity.AquaFishEntity)
	Entity ID: 21100
	Entity Name: Muskellunge
	Entity's Exact location: 159.50, 61.82, 171.50
	Entity's Block location: World: (159,61,171), Chunk: (at 15,3,11 in 9,10; contains blocks 144,0,160 to 159,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 2 total; [ServerPlayerEntity['Shecil'/8840, l='world', x=368.10, y=85.00, z=-1211.04], ServerPlayerEntity['Aeyos'/18613, l='world', x=163.15, y=50.00, z=194.37]]
	Chunk stats: ServerChunkCache: 3740
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: 123
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (176,68,212), Chunk: (at 0,4,4 in 11,13; contains blocks 176,0,208 to 191,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 606844 game time, 294700 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 24024 (now: false), thunder time: 62291 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by GirafiStudios** [comment]
The crash is caused by the mod Performant it seems.
The crash is never at any point happening in Aquaculture
