### ISSUE TITLE
Crash when using /tp

### ISSUE THREAD

**Issue by Reshy** [TeamMetallurgy/Aquaculture#274]
-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:683) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.addOrGet(ObjectOpenCustomHashSet.java:360) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at net.minecraft.client.renderer.RenderType$Type.func_228676_c_(RenderType.java:531) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType$Type.func_228675_b_(RenderType.java:509) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_228633_a_(RenderType.java:270) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_228632_a_(RenderType.java:266) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_239265_a_(RenderType.java:181) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType$Type.func_239275_a_(RenderType.java:524) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$4044/1791747201.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraft.client.renderer.RenderType$Type.<init>(RenderType.java:523) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType$Type.func_228676_c_(RenderType.java:531) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType$Type.func_228675_b_(RenderType.java:509) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_228633_a_(RenderType.java:270) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_230167_a_(RenderType.java:94) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.RenderType.func_228640_c_(RenderType.java:98) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:charm.mixins.json:RenderTypeMixin,pl:mixin:APP:charm.mixins.json:accessor.RenderTypeAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.model.SegmentedModel$$Lambda$15191/2023553481.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.model.Model.func_228282_a_(SourceFile:26) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_230496_a_(LivingRenderer.java:140) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:APP:charm.mixins.json:accessor.LivingRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:116) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obfuscate.mixins.json:client.LivingRendererMixin,pl:mixin:APP:charm.mixins.json:accessor.LivingRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at com.teammetallurgy.aquaculture.client.renderer.entity.AquaFishRenderer.render(AquaFishRenderer.java:63) ~[?:1.16.5-2.1.21] {re:classloading}
	at com.teammetallurgy.aquaculture.client.renderer.entity.AquaFishRenderer.func_225623_a_(AquaFishRenderer.java:20) ~[?:1.16.5-2.1.21] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: aquaculture:pollock (com.teammetallurgy.aquaculture.entity.AquaFishEntity)
	Entity ID: 111154
	Entity Name: Pollock
	Entity's Exact location: 1011.25, 49.09, 1034.84
	Entity's Block location: World: (1011,49,1034), Chunk: (at 3,3,10 in 63,64; contains blocks 1008,0,1024 to 1023,255,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: -0.02, 0.00, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

**Comment by sscards55** [comment]
Can you post the full crash log? This give no information useful for debugging.

**Comment by GirafiStudios** [comment]
Closing, because of insufficient information provided.
