### ISSUE TITLE
1.18.2 Aquaculture crash on Forge 40.0.12

### ISSUE THREAD

**Issue by ajermaky** [TeamMetallurgy/Aquaculture#312]
# Issue 
Updating to new Forge Version 40.0.12 with Aquaculture-1.18.2-2.3.4.jar mod causes following crash:
```
Mod List: 
		server-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.0.12-universal.jar                |Forge                         |forge                         |40.0.12             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.18.2-2.3.4.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.4        |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: f35a5063-6974-4872-b798-a68c031330ae
	FML: 40.0
	Forge: net.minecraftforge:40.0.12[23:54:51] [main/ERROR]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Aquaculture 2 (aquaculture) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.2-40.0.12.jar%2341!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.2-40.0.12.jar%2341!/:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.2-40.0.12.jar%2341!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[fmlcore-1.18.2-40.0.12.jar%2341!/:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:177) ~[fmlcore-1.18.2-40.0.12.jar%2341!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.0.12-universal.jar%2344!/:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220228.144236-srg.jar%2340!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.2-40.0.12.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
2022-03-12T23:54:52.152Z	INFO	mc-server-runner	Done
                                                                   
```

# How To Replicate
Install forge 40.0.12 server w/ Aquaculture-1.18.2-2.3.4.jar

**Comment by GirafiStudios** [comment]
Unable to reproduce. Does not make any sense either as Forge 40.0.12 makes changes to the resource loader listener, which Aquaculture does not use at all.
