### ISSUE TITLE
Version for 1.18.2 on Server bot working

### ISSUE THREAD

**Issue by yoozicq11504824** [TeamMetallurgy/Aquaculture#314]

**Comment by yoozicq11504824** [comment]
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/8250535/latest.log)

**Comment by yoozicq11504824** [comment]
tried win 11 and Linux with same result

**Comment by yoozicq11504824** [comment]
---- Minecraft Crash Report ----
// There are four lights!

Time: 15.03.22, 06:23
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.0.15-universal.jar%2344!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.0.15-universal.jar%2344!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220228.144236-srg.jar%2340!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.2-40.0.15.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD aquaculture --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.15.jar%2342!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.15.jar%2341!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
		at com.teammetallurgy.aquaculture.init.AquaEntities.<clinit>(AquaEntities.java:35) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:65) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:54) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.init.AquaItems.<clinit>(AquaItems.java:70) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.init.AquaBlocks.register(AquaBlocks.java:46) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.init.AquaBlocks.<clinit>(AquaBlocks.java:24) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.Aquaculture.registerDeferredRegistries(Aquaculture.java:70) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at com.teammetallurgy.aquaculture.Aquaculture.<init>(Aquaculture.java:48) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.15.jar%2342!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.15.jar%2341!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: Aquaculture-1.18.2-2.3.4.jar
	Failure message: Aquaculture 2 (aquaculture) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.2-2.3.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.teammetallurgy.aquaculture.init.AquaEntities.<clinit>(AquaEntities.java:35) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:65) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:54) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaItems.<clinit>(AquaItems.java:70) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaBlocks.register(AquaBlocks.java:46) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaBlocks.<clinit>(AquaBlocks.java:24) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.Aquaculture.registerDeferredRegistries(Aquaculture.java:70) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at com.teammetallurgy.aquaculture.Aquaculture.<init>(Aquaculture.java:48) ~[Aquaculture-1.18.2-2.3.4.jar%2338!/:1.18.2-2.3.4] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.15.jar%2342!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.15.jar%2341!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1176317936 bytes (1121 MiB) / 2529165312 bytes (2412 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4,00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192,00
	Memory slot #2 clockSpeed (GHz): 2,67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192,00
	Memory slot #3 clockSpeed (GHz): 2,67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37544,34
	Virtual memory used (MB): 17632,83
	Swap memory total (MB): 4864,00
	Swap memory used (MB): 78,91
	JVM Flags: 1 total; -Xmx5G
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.0.15-universal.jar                |Forge                         |forge                         |40.0.15             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.18.2-2.3.4.jar                      |Aquaculture 2                 |aquaculture                   |1.18.2-2.3.4        |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 7e7420c7-9b13-426e-8804-d05fa73abec6
	FML: 40.0
	Forge: net.minecraftforge:40.0.15

**Comment by GirafiStudios** [comment]
Another time, please use gist.github.com to paste the crashlog in to :)
Looks like there is an import for Lists that does not exists in all instances.
Could I get you to test if that fixes it for you? :) As I´m unable to reproduce the issue myself

I´ve attached the build with the fix in the attatched zip file. Make sure to unzip it.

[Aquaculture-1.18.2-2.3.5.jar.zip](https://github.com/TeamMetallurgy/Aquaculture/files/8286458/Aquaculture-1.18.2-2.3.5.jar.zip)
.
