### ISSUE TITLE
aquaculture 2 mod not working for my minecraft, I can't read this so I don't know what's wrong

### ISSUE THREAD

**Issue by Antzoopoo** [TeamMetallurgy/Aquaculture#391]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/27/23, 8:38 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19-41.1.0-universal.jar%23188!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19-41.1.0-universal.jar%23188!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:596) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:555) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.teammetallurgy.aquaculture.init.AquaEntities.<clinit>(AquaEntities.java:25) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
-- MOD aquaculture --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23185!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23184!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/antho/curseforge/minecraft/Instances/My Fav Mods/mods/Aquaculture-1.19-2.4.0.jar
	Failure message: Aquaculture 2 (aquaculture) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19-2.4.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: ENTITIES
Stacktrace:
	at com.teammetallurgy.aquaculture.init.AquaEntities.<clinit>(AquaEntities.java:25) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:62) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.init.FishRegistry.register(FishRegistry.java:51) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaItems.<clinit>(AquaItems.java:69) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaBlocks.register(AquaBlocks.java:47) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.init.AquaBlocks.<clinit>(AquaBlocks.java:25) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.Aquaculture.registerDeferredRegistries(Aquaculture.java:81) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at com.teammetallurgy.aquaculture.Aquaculture.<init>(Aquaculture.java:53) ~[Aquaculture-1.19-2.4.0.jar%23147!/:1.19-2.4.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23185!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23184!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 210032184 bytes (200 MiB) / 704643072 bytes (672 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2503
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33718.29
	Virtual memory used (MB): 16084.52
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 627.98
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m
	OptiFine Version: OptiFine_1.19_HD_U_H9
	OptiFine Build: 20220731-224510
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 528.49
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.7-mc1.19forge.jar                 |Macaw's Bridges               |mcwbridges                    |2.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19-11.1.9.jar     |EnchantmentDescriptions       |enchdesc                      |11.1.9              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19forge.jar                  |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19-forge-11.1.1.239.jar                     |Just Enough Items             |jei                           |11.1.1.239          |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.5-forge-mc1.19.jar     |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.19-4.0.0.jar                |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		goblintraders-1.7.3-1.19.jar                      |Goblin Traders                |goblintraders                 |1.7.3               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.1.1-mc1.19forge.jar                 |Macaw's Windows               |mcwwindows                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.2-mc1.19.2.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		ecologics-forge-1.19-2.1.8.1.jar                  |Ecologics                     |ecologics                     |2.1.8.1             |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.3.1.jar                 |Waystones                     |waystones                     |11.3.1              |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.19.0-3.7.jar                      |Villager Names                |villagernames                 |3.7                 |COMMON_SET|Manifest: NOSIGNATURE
		duckling-2.0.5-forge.jar                          |Duckling                      |duckling                      |2.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.0-4.30.jar                        |Collective                    |collective                    |4.30                |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19-9.0.0+7.jar                     |Clumps                        |clumps                        |9.0.0+7             |COMMON_SET|Manifest: NOSIGNATURE
		advancednetherite-1.13.5-1.19.jar                 |Advanced Netherite            |advancednetherite             |1.13.5              |COMMON_SET|Manifest: NOSIGNATURE
		PigPen-Forge-1.19-9.1.3.jar                       |PigPen                        |pigpen                        |9.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5-forge.jar                   |Journeymap                    |journeymap                    |5.8.5               |COMMON_SET|Manifest: NOSIGNATURE
		EarthMobs-1.19-2.3.4.jar                          |Earth Mobs Mod                |earthmobsmod                  |1.19-2.3.4          |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.19-8.0.0.19.jar                   |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		bettervillage-forge-1.19-2.1.0.jar                |Better village                |bettervillage                 |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		backpacked-2.1.10-1.19.jar                        |Backpacked                    |backpacked                    |2.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.19-11.1.0.jar        |Farming for Blockheads        |farmingforblockheads          |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19-14.2.10.jar                  |Bookshelf                     |bookshelf                     |14.2.10             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.19-1.5.1.jar                     |Guard Villagers               |guardvillagers                |1.19-1.5.1          |COMMON_SET|Manifest: NOSIGNATURE
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-5.14.68-forge.jar                    |Architectury                  |architectury                  |5.14.68             |COMMON_SET|Manifest: NOSIGNATURE
		animal_feeding_trough-1.0.3+1.19-forge.jar        |Animal Feeding Trough         |animal_feeding_trough         |1.0.3+1.19-forge    |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.1.0-mc1.19forge.jar               |Macaw's Furniture             |mcwfurnitures                 |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |COMMON_SET|Manifest: NOSIGNATURE
		trashcans-1.0.17a-forge-mc1.19.jar                |Trash Cans                    |trashcans                     |1.0.17a             |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.19-1.18.1.2.jar                         |Carry On                      |carryon                       |1.18.1.2            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.1.0-universal.jar                   |Forge                         |forge                         |41.1.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		Aquaculture-1.19-2.4.0.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.0          |ERROR     |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.28.jar                    |GeckoLib                      |geckolib3                     |3.1.28              |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.0.5-mc1.19forge.jar                  |Macaw's Lights and Lamps      |mcwlights                     |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 80f50642-191f-415c-b5ff-ae2266b89e76
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Comment by GirafiStudios** [comment]
Please update Aquaculture 2 to the latest for your Minecraft version.
Which in this case would be version 2.4.5
Can be downloaded here: https://www.curseforge.com/minecraft/mc-mods/aquaculture/files/3918077

**Comment by Antzoopoo** [comment]
is version 2.4.8 not the latest one?
