### ISSUE TITLE
Server kicks me and anyone else that grabs the neptunium fillet knife out of the bounty chest.

### ISSUE THREAD

**Issue by JettyQuin** [TeamMetallurgy/Aquaculture#400]

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 & Mincraft Forge are you on?
Also please provide the logs with the error.

**Comment by JettyQuin** [comment]
Aquaculture 2 version is 1.19.2-2.4.8 and the forge I’m using is 43.2.8. Here is the server log.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by GirafiStudios** [comment]
I don't see any server log, that's attatched :)

**Comment by GirafiStudios** [comment]
Unable to reproduce & can't really do anything without a log.

**Comment by MsAshie** [comment]
Hi there, Im having this same issue, both server side and singleplayer worlds. 

Im running Forge: 
https://gyazo.com/6aed2ffc29ae4770c8836499464fc17f

The single player world will load, but if I try and take the Fillet knife (when in creative) it crashes the whole game, and I get the error: 
https://gyazo.com/ceca40dc3c1c40cdf257b32a17919a21

On my server, if the Fillet knife is attempted to be taken from the bounty chest, it also crashes, im unable to recreate the crash log because it will not let me back into the server unless i completely remove my UUID from the server files. 

Recreating the server with additional modpacks of:
- Artifacts 
- Botania
- Create 
- Sophisticated Backpacks
- Pneumaticcraft Repressurized

The client will attempt to load, but then crash and give the error:

https://gyazo.com/a8e4f028fd2f00b8f9eed17320b51921

Hope these details help, Aquaculture 2 is an awesome mod and I'd love to be able to get to the bottom of it so we can keep playing it :)

**Comment by GirafiStudios** [comment]
Thanks for providing additional information!
Does this happen as soon as you hold your mouse over the Neptunium Fillet Knife in Neptune's Bounty? Or is it first when you actually try to take it?

**Comment by MsAshie** [comment]
hovering the mouse over it is fine, but as soon as you try and take it / move it, its crashes.

**Comment by GirafiStudios** [comment]
That's even more peculiar then, as it's not the tooltip then.
I'll try to look into it again :)

**Comment by MsAshie** [comment]
I dont know if it helps, but whats even weirder.. is that on my friends server we run Valhelisa 3 (which has Aquaculture included in the modpack) .. we have added Sohphisticated backpacks manually, and we dont have any issues with the knife at all, I can pick it up, move it, use it.. no issue at all. 

https://gyazo.com/e34efe0f561b53d8f74a7252a9f2c39d

**Comment by GirafiStudios** [comment]
That's on Minecraft 1.16.4 though, the code for the fillet knifes have changed since then as well :)

**Comment by MsAshie** [comment]
ahh well that makes sense!

**Comment by GirafiStudios** [comment]
I'm unable to reproduce this on 1.19.4, which is what the master branch is on atm.
The problem with going back to 1.19.2, is that I don't have a branch/workspace for that specific version. Usually minor versions of Minecraft is more of less compatible between each other (Or minor changes only). That have not really been the case with the 1.19 cycle though, as multiple of the minor versions have brought breaking changes for many mods.

My best guess is that one of the other mods, don't like that the Neptunium Fillet Knife is not damagable. Could potientially be Sohphisticated Backpacks, if it tries to move the Fillet Knife into the backpack? Not familiar with the mod myself.

**Comment by PvtFudgepants** [comment]
Not sure if I should've made a new thing or commented here, but I'm also getting this exact same issue, but on 1.19.2. Was anything ever discovered about why this might happen? I had to open the player's file in an nbt editor and remove the knife and he was once again able to login.

**Comment by TigerWalts** [comment]
Late to the party on this but here's the error in the server log (with mixins listed):

```
01.05 12:07:44 [Server] INFO net.minecraft.ReportedException: Ticking player
01.05 12:07:44 [Server] INFO at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:revampedwolf.mixins.json:server.ServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:immersive_aircraft.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:dolt_compat.mixins.json:ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:flightlib.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenServer,pl:mixin:APP:ad_astra-common.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:tetra.mixins.json:MixinServerPlayNetHandler,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerPlayNetworkHandler,pl:mixin:APP:toofast.mixins.json:MixinServerNetPlayHandler,pl:mixin:APP:quark.mixins.json:accessor.AccessorServerGamePacketListenerImpl,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,re:classloading,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,re:classloading,pl:mixin:APP:luna.mixins.json:ServerNetworkIoMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:create_new_age.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
01.05 12:07:44 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
01.05 12:07:44 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128441_(String)" because the return value of "net.minecraft.world.item.ItemStack.m_41783_()" is null
01.05 12:07:44 [Server] INFO at net.minecraft.world.item.Item.handler$zio000$GE$inventoryTick(Item.java:2037) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ItemMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_registry_alloc.DelegateHolderMixin,pl:mixin:APP:supplementaries-common.mixins.json:ItemMixin,pl:mixin:APP:goodending.mixins.json:ItemMixin,pl:mixin:APP:kiwi.mixins.json:ItemAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ItemMixin,pl:mixin:APP:aether_redux.mixins.json:common.item.ItemMixin,pl:mixin:APP:aether.mixins.json:common.ItemMixin,pl:mixin:APP:bookshelf.common.mixins.json:item.AccessorItem,pl:mixin:APP:architectury-common.mixins.json:inject.MixinItem,pl:mixin:APP:blueprint.mixins.json:ItemInvokerMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemMixin,pl:mixin:APP:quark.mixins.json:ItemMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.item.Item.m_6883_(Item.java) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:ItemMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_registry_alloc.DelegateHolderMixin,pl:mixin:APP:supplementaries-common.mixins.json:ItemMixin,pl:mixin:APP:goodending.mixins.json:ItemMixin,pl:mixin:APP:kiwi.mixins.json:ItemAccess,pl:mixin:APP:ftblibrary-common.mixins.json:ItemMixin,pl:mixin:APP:aether_redux.mixins.json:common.item.ItemMixin,pl:mixin:APP:aether.mixins.json:common.ItemMixin,pl:mixin:APP:bookshelf.common.mixins.json:item.AccessorItem,pl:mixin:APP:architectury-common.mixins.json:inject.MixinItem,pl:mixin:APP:blueprint.mixins.json:ItemInvokerMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemMixin,pl:mixin:APP:quark.mixins.json:ItemMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:508) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,xf:fml:improvableskills:ItemStackHurtHook,xf:fml:forge:itemstack,re:classloading,xf:fml:improvableskills:ItemStackHurtHook,xf:fml:forge:itemstack,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:extendedgears-common.mixins.json:MixinItemStack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:228) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:carryon.mixins.json:InventoryMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerInventory,pl:mixin:APP:moonlight-common.mixins.json:InventoryMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:personality.mixins.json:PlayerMixin,pl:mixin:APP:aether_redux.mixins.json:common.entity.PlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:tetra.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:PlayerEntityMixin,pl:mixin:APP:bygonenether.mixins.json:NoAxeDisableModShieldMixin,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:shieldexp.mixins.json:PlayerMixin,pl:mixin:APP:spyglass_improvements.mixins.json:PlayerMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:easymagic.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:forbidden_arcanus.mixins.json:PlayerMixin,pl:mixin:APP:mixins.irons_spellbooks.json:PlayerMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinPlayer,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_livingentity_addeffect,xf:fml:openpartiesandclaims:xaero_pac_livingentity_die,xf:fml:openpartiesandclaims:xaero_pac_livingentity_dropalldeathloot,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin,pl:mixin:APP:environmental.mixins.json:LivingEntityMixin,pl:mixin:APP:autoleveling.mixins.json:LivingEntityAccessor,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:goodending.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:personality.mixins.json:LivingEntityMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinEntityRiding,pl:mixin:APP:aether_redux.mixins.json:common.entity.LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:all_bark_all_bite.mixins.json:LivingEntityAccessor,pl:mixin:APP:all_bark_all_bite.mixins.json:LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LivingEntityAccessor,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:shieldexp.mixins.json:LivingEntityMixin,pl:mixin:APP:cataclysm.mixins.json:LivingEntityMixin,pl:mixin:APP:spirit.common.mixins.json:LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:thinair.common.mixins.json:LivingEntityMixin,pl:mixin:APP:thinair.forge.mixins.json:LivingEntityForgeMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:mixins.irons_spellbooks.json:LivingEntityMixin,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_player_mayuseitemat,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:personality.mixins.json:PlayerMixin,pl:mixin:APP:aether_redux.mixins.json:common.entity.PlayerMixin,pl:mixin:APP:ad_astra-common.mixins.json:PlayerMixin,pl:mixin:APP:tetra.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:immersive_aircraft.mixins.json:PlayerEntityMixin,pl:mixin:APP:bygonenether.mixins.json:NoAxeDisableModShieldMixin,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:shieldexp.mixins.json:PlayerMixin,pl:mixin:APP:spyglass_improvements.mixins.json:PlayerMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:easymagic.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:forbidden_arcanus.mixins.json:PlayerMixin,pl:mixin:APP:mixins.irons_spellbooks.json:PlayerMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinPlayer,pl:mixin:APP:create_enchantment_industry.mixins.json:PlayerMixin,pl:mixin:A}
01.05 12:07:44 [Server] INFO at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23623!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:betterchunkloading.mixins.json:PlayerChunkDataMixin,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:revampedwolf.mixins.json:server.ServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:immersive_aircraft.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:dolt_compat.mixins.json:ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
01.05 12:07:44 [Server] Server thread/WARN 9 more
```

I suspect that Forbidden Arcanus is the cause as it has a mixin on the `inventoryTick` that tries to access the item's Damage value but the item has no NBT data at all, let alone a damage value:

- https://github.com/stal111/Forbidden-Arcanus/blob/d6a3681dd04480fd57e047a10529612559050a1c/src/main/java/com/stal111/forbidden_arcanus/core/mixin/ItemMixin.java#L24-L28

**Comment by GirafiStudios** [comment]
Is this for 1.19.2 as well?

**Comment by TigerWalts** [comment]
That was on 1.19.2.

It happened on the **STEAMPUNK [LPS] v22HF** modpack with Aquaculture 1.19.2-2.4.8 added.

Later versions of Aquaculture are fine as the fillet knife item has damageable variants and so it has a damage value. The Neptunium variant gets a damage value of `-1`.

**Comment by GirafiStudios** [comment]
Just looked further into this & there is no changes to the fillet knifes in newer versions at all. I was also not able to reproduce it with just Aquaculture, so for sure caused by some mod incompatibility.

I've made a 1.19.2 version of AQ2, that brings it up to parity with the 1.19.4 version, as a final release for 1.19.2.
