### ISSUE TITLE
Fishing in non-vanilla biomes == uh oh

### ISSUE THREAD

**Issue by joklbash** [TeamMetallurgy/Aquaculture#47]
MC 1.12.2
Forge 14.23.4.2715
Aqua 1.6.5

When I fish in a vanilla biome, the rods work as expected. When I fish in a non-vanilla biome, such as BoP or Thaum's magical place, the first click doesn't seem to want to respond and a second click causes the below error in the console. Happens in SP and server.

[17:44:09] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
	at com.teammetallurgy.aquaculture.loot.BiomeType.getBiomeType(BiomeType.java:46) ~[BiomeType.class:?]
	at com.teammetallurgy.aquaculture.loot.FishLoot.getRandomJunk(FishLoot.java:90) ~[FishLoot.class:?]
	at com.teammetallurgy.aquaculture.handlers.EntityCustomFishHook.func_146034_e(EntityCustomFishHook.java:506) ~[EntityCustomFishHook.class:?]
	at com.teammetallurgy.aquaculture.items.ItemAquacultureFishingRod.func_77659_a(ItemAquacultureFishingRod.java:70) ~[ItemAquacultureFishingRod.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by GirafiStudios** [comment]
Fixed by https://github.com/TeamMetallurgy/Aquaculture/commit/6aaaa8ff990fb294031bd6ec37dcd3917d23b21e
